#!/usr/bin/env python3
"""
3370 Great North Road - Mixed Residential Scheme
Citadel-branded concept-development pack (A4 portrait, 12 pages).

Brand helpers (rook, wordmark, footer, header, sect, wrap, mtable, bar, kv)
are adapted from the proven build_pack_reference.py from this project.
Numbers are the LOCKED figures in data/mixed_scheme.json (section 2 of the brief).
Schematic figures are generated by build_visuals.py and embedded honestly with the
mandatory rule-0 caption under every figure.
"""
import os
import json
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

# ---- Brand palette --------------------------------------------------------
GREEN = HexColor('#727C60'); BLACK = HexColor('#000000'); WHITE = HexColor('#FFFFFF')
LIGHT_GREEN = HexColor('#E8EBE4'); MID_GREEN = HexColor('#9BA38D'); DARK_GREEN = HexColor('#3A4030')
TEXT_DARK = HexColor('#2D2D2D'); TEXT_MID = HexColor('#555555'); TEXT_LIGHT = HexColor('#808080')
FLAG = HexColor('#8B3A2F')

W, H = A4
ML, MR, MT, MB = 45, 45, 55, 50
CW = W - ML - MR

HERE = os.path.dirname(os.path.abspath(__file__))
FIGDIR = os.path.join(HERE, "..", "figures")
OUT = os.path.join(HERE, "..", "3370 Great North Road - Mixed Residential Scheme.pdf")
DATA = json.load(open(os.path.join(HERE, "mixed_scheme.json")))

TOTAL = 12
CAP = ("Indicative schematic only — not to scale, not for construction or resource "
       "consent. Architectural design to be prepared by a registered architect.")


def money(n):
    return "${:,}".format(int(round(n)))


# ===========================================================================
# Brand helpers (adapted from build_pack_reference.py)
# ===========================================================================
def rook(c, x, y, w, colour):
    h = w * (1788.0 / 2000.0); c.saveState(); c.setFillColor(colour)
    tw = w * 0.26; gap = (w - 3 * tw) / 2.0; bh = h * 0.60
    c.rect(x, y, w, bh * 0.5, fill=1, stroke=0)
    for i in range(3):
        c.rect(x + i * (tw + gap), y, tw, bh, fill=1, stroke=0)
    for i in range(2):
        gx = x + tw + i * (tw + gap); p = c.beginPath()
        p.moveTo(gx, y + bh * 0.5); p.lineTo(gx + gap, y + bh * 0.5)
        p.lineTo(gx + gap / 2.0, y + h); p.close()
        c.drawPath(p, fill=1, stroke=0)
    cx = x + tw + gap + tw / 2.0; p = c.beginPath()
    p.moveTo(x + tw + gap, y + bh); p.lineTo(x + 2 * tw + gap, y + bh)
    p.lineTo(cx, y + h * 1.05); p.close()
    c.drawPath(p, fill=1, stroke=0); c.restoreState()


def wm(c, x, y, size, colour):
    c.setFont('Helvetica-Bold', size); c.setFillColor(colour); c.drawString(x, y, 'Citadel.')


def footer(c, pn):
    y = MB - 25
    c.setStrokeColor(GREEN); c.setLineWidth(0.5); c.line(ML, y + 12, W - MR, y + 12)
    c.setFont('Helvetica', 7); c.setFillColor(TEXT_LIGHT)
    c.drawString(ML, y, '3370 Great North Road  -  Mixed Residential Scheme  -  A Citadel Capital Entity')
    c.drawRightString(W - MR, y, f'Page {pn} of {TOTAL}')
    rook(c, W / 2 - 7, y - 3, 14, BLACK)


def header(c, y, title, sub):
    c.setFont('Helvetica-Bold', 14); c.setFillColor(BLACK); c.drawString(ML, y, title); y -= 17
    c.setFont('Helvetica', 10); c.setFillColor(GREEN); c.drawString(ML, y, sub); y -= 8
    c.setStrokeColor(GREEN); c.setLineWidth(0.75); c.line(ML, y, W - MR, y); return y - 20


def sect(c, y, t):
    c.setFont('Helvetica-Bold', 9.5); c.setFillColor(BLACK); c.drawString(ML + 2, y, t)
    c.setStrokeColor(GREEN); c.setLineWidth(0.75)
    c.line(ML + 2, y - 3, ML + 2 + c.stringWidth(t, 'Helvetica-Bold', 9.5), y - 3); return y - 16


def wrap(c, text, x, y, mw, font='Helvetica', size=9, lead=12.5, colour=TEXT_DARK):
    c.setFont(font, size); c.setFillColor(colour); line = ''
    for word in text.split(' '):
        t = (line + ' ' + word).strip()
        if c.stringWidth(t, font, size) > mw and line:
            c.drawString(x, y, line); y -= lead; line = word
        else:
            line = t
    if line:
        c.drawString(x, y, line); y -= lead
    return y


def wrap_center(c, text, cx, y, mw, font='Helvetica', size=7.2, lead=9.5, colour=TEXT_LIGHT):
    c.setFont(font, size); c.setFillColor(colour); line = ''
    for word in text.split(' '):
        t = (line + ' ' + word).strip()
        if c.stringWidth(t, font, size) > mw and line:
            c.drawCentredString(cx, y, line); y -= lead; line = word
        else:
            line = t
    if line:
        c.drawCentredString(cx, y, line); y -= lead
    return y


def bullet(c, head, body, y, mw=CW - 4, x=ML + 2):
    c.setFont('Helvetica-Bold', 9); c.setFillColor(GREEN); c.drawString(x, y, head)
    hw = c.stringWidth(head + '  ', 'Helvetica-Bold', 9)
    c.setFont('Helvetica', 9); c.setFillColor(TEXT_DARK)
    line = ''; first = True; xs = x + hw
    for word in body.split(' '):
        t = (line + ' ' + word).strip(); avail = (mw - hw) if first else mw
        if c.stringWidth(t, 'Helvetica', 9) > avail and line:
            c.drawString(xs if first else x, y, line); y -= 12; line = word; first = False
        else:
            line = t
    if line:
        c.drawString(xs if first else x, y, line); y -= 12
    return y - 6


def mtable(c, y, rows, total=None, head=None):
    if head:
        c.setFillColor(GREEN); c.rect(ML + 2, y - 4, CW - 4, 16, fill=1, stroke=0)
        c.setFont('Helvetica-Bold', 8); c.setFillColor(WHITE)
        c.drawString(ML + 8, y, head[0]); c.drawRightString(W - MR - 8, y, head[1]); y -= 20
    for label, val in rows:
        c.setFont('Helvetica', 8.5); c.setFillColor(TEXT_DARK)
        c.drawString(ML + 8, y, label); c.drawRightString(W - MR - 8, y, val); y -= 14
    if total:
        c.setStrokeColor(GREEN); c.setLineWidth(0.75); c.line(ML + 8, y + 4, W - MR - 8, y + 4); y -= 6
        c.setFont('Helvetica-Bold', 9.5); c.setFillColor(BLACK)
        c.drawString(ML + 8, y, total[0]); c.drawRightString(W - MR - 8, y, total[1]); y -= 16
    return y


def bar(c, y, label, val):
    c.setFillColor(GREEN); c.rect(ML + 2, y - 6, CW - 4, 22, fill=1, stroke=0)
    c.setFont('Helvetica-Bold', 11); c.setFillColor(WHITE)
    c.drawString(ML + 10, y, label); c.drawRightString(W - MR - 10, y, val); return y - 26


def kv(c, y, rows, split=0.52, rh=15, bold=None):
    bold = bold or set()
    for i, (k, v) in enumerate(rows):
        if i % 2 == 0:
            c.setFillColor(LIGHT_GREEN); c.rect(ML + 2, y - 3, CW - 4, rh, fill=1, stroke=0)
        b = k in bold
        c.setFont('Helvetica-Bold' if b else 'Helvetica', 8.5)
        c.setFillColor(BLACK if b else TEXT_DARK); c.drawString(ML + 8, y, k)
        c.setFont('Helvetica-Bold' if b else 'Helvetica', 8.5); c.drawString(ML + CW * split, y, v)
        y -= rh
    return y


def _aligned(c, x, y, text, a):
    if a == 'l':
        c.drawString(x, y, text)
    elif a == 'r':
        c.drawRightString(x, y, text)
    else:
        c.drawCentredString(x, y, text)


def coltable(c, y, headers, rows, colx, aligns, highlight_idx=None,
             rowh=14, headh=16, total_idx=None):
    c.setFillColor(GREEN); c.rect(ML + 2, y - 4, CW - 4, headh, fill=1, stroke=0)
    c.setFont('Helvetica-Bold', 8); c.setFillColor(WHITE)
    for h, x, a in zip(headers, colx, aligns):
        _aligned(c, x, y, h, a)
    y -= headh + 4
    for i, row in enumerate(rows):
        is_total = (total_idx is not None and i == total_idx)
        is_hl = (highlight_idx is not None and i == highlight_idx)
        if is_hl:
            c.setFillColor(MID_GREEN); c.rect(ML + 2, y - 3, CW - 4, rowh, fill=1, stroke=0)
            font, col = 'Helvetica-Bold', WHITE
        elif is_total:
            c.setStrokeColor(GREEN); c.setLineWidth(0.75); c.line(ML + 8, y + rowh - 3, W - MR - 8, y + rowh - 3)
            font, col = 'Helvetica-Bold', BLACK
        else:
            if i % 2 == 0:
                c.setFillColor(LIGHT_GREEN); c.rect(ML + 2, y - 3, CW - 4, rowh, fill=1, stroke=0)
            font, col = 'Helvetica', TEXT_DARK
        c.setFont(font, 8.5); c.setFillColor(col)
        for cell, x, a in zip(row, colx, aligns):
            _aligned(c, x, y, cell, a)
        y -= rowh
    return y


def figure(c, y, name, disp_w, x=None, max_h=None, caption=True):
    img = ImageReader(os.path.join(FIGDIR, name))
    iw, ih = img.getSize()
    scale = disp_w / iw
    if max_h and ih * scale > max_h:
        scale = max_h / ih
    w, h = iw * scale, ih * scale
    if x is None:
        x = ML + (CW - w) / 2.0
    c.drawImage(img, x, y - h, width=w, height=h, mask='auto')
    yy = y - h - 8
    if caption:
        yy = wrap_center(c, CAP, x + w / 2.0, yy, w + 40)
    return yy, (x, w, h)


def pimg(c, name, x, y_top, box_w, box_h):
    """Fit a precedent photo inside a box (preserve aspect), thin border, centered in box."""
    img = ImageReader(os.path.join(FIGDIR, 'precedents', name))
    iw, ih = img.getSize()
    scale = min(box_w / iw, box_h / ih)
    w, h = iw * scale, ih * scale
    px = x + (box_w - w) / 2.0
    c.drawImage(img, px, y_top - h, width=w, height=h, mask='auto')
    c.setStrokeColor(MID_GREEN); c.setLineWidth(0.6); c.rect(px, y_top - h, w, h, fill=0, stroke=1)
    return px, w, h


def flagbox(c, y, heading, text, height=58):
    c.setStrokeColor(FLAG); c.setLineWidth(1.2); c.line(ML + 2, y + 6, ML + 2, y - height)
    c.setFont('Helvetica-Bold', 8.5); c.setFillColor(FLAG); c.drawString(ML + 10, y, heading)
    y -= 13
    y = wrap(c, text, ML + 10, y, CW - 12, size=8.5, lead=11, colour=TEXT_MID)
    return y


# ===========================================================================
# Build
# ===========================================================================
c = canvas.Canvas(OUT, pagesize=A4)

# ----- P1 COVER -----
c.setFillColor(GREEN); c.rect(0, 0, W, H, fill=1, stroke=0)
cm = 50
wm(c, cm, H - 70, 30, WHITE)
ny = H * 0.56
c.setFont('Helvetica-Bold', 29); c.setFillColor(BLACK)
c.drawString(cm, ny, '3370 Great North Road')
c.setFont('Helvetica-Bold', 22); c.setFillColor(WHITE)
c.drawString(cm, ny - 32, 'Mixed Residential Scheme')
c.setFont('Helvetica', 13); c.setFillColor(DARK_GREEN)
c.drawString(cm, ny - 62, '26 design-led residences  |  Glen Eden, Auckland')
c.setFont('Helvetica', 10); c.setFillColor(DARK_GREEN)
c.drawString(cm, ny - 80, 'Concept, Massing, Feasibility, Market & Financing')
c.drawString(cm, ny - 94, 'Prepared under the Citadel Acquisition Engine')
c.setStrokeColor(BLACK); c.setLineWidth(0.75); c.line(cm, ny - 106, cm + 340, ny - 106)
c.setFont('Helvetica', 8.5); c.setFillColor(DARK_GREEN)
c.drawString(cm, ny - 126, 'June 2026  -  Internal  -  Strictly Private & Confidential')
wm(c, cm, MB, 11, BLACK)
c.setFont('Helvetica', 8); c.setFillColor(BLACK); c.drawString(cm, MB - 13, 'citadel.capital')
rook(c, W - cm - 42, MB - 5, 42, BLACK)
c.showPage()

# ----- P2 EXECUTIVE SUMMARY -----
y = H - MT
y = header(c, y, 'Executive Summary', 'A two-product residential scheme for two buyer pools')
y = wrap(c, 'This paper sets out a mixed residential scheme for the 809 m2 THAB site: 26 '
            'design-led residences across a four-level walk-up, built as a cost-efficient '
            'brutalist shell and finished to a distinctive, brand-led interior standard. The '
            'scheme deliberately blends two products - 16 single one-bedroom residences and '
            '10 dual-key residences, each containing two lockable studios - to address two '
            'distinct buyer pools and de-risk the sell-down.', ML + 2, y, CW - 4)
y -= 4
y = wrap(c, 'At adopted prices of $499,000 (one-bedroom) and $599,000 (dual-key), the scheme '
            'returns a 24.7% development margin, 142% return on equity, and supports a residual '
            'land value of $1,761 / m2 - above the $1,400 / m2 acquisition position. The '
            'dual-key product, generating two income streams, out-yields the one-bedroom '
            '(5.6% vs 5.0% gross), so its higher price is justified by income rather than '
            'optimism.', ML + 2, y, CW - 4)
y -= 10
y = bar(c, y, 'Adopted scheme: 26 residences, two products', '24.7% margin')
y -= 8
y = sect(c, y, 'HEADLINE NUMBERS (ex-GST, at $605k land entry)')
y = kv(c, y, [
    ('Residences', '26  (16 one-bed + 10 dual-key)'),
    ('Gross realisation (incl GST)', money(DATA['feasibility_ex_gst']['grv_incl'])),
    ('Gross realisation (ex-GST)', money(DATA['feasibility_ex_gst']['grv_ex'])),
    ('Total development cost', money(DATA['feasibility_ex_gst']['total_cost'])),
    ('Development profit', money(DATA['feasibility_ex_gst']['profit'])),
    ('Development margin', '24.7%'),
    ('Equity (25%) / Return on equity', money(DATA['feasibility_ex_gst']['equity']) + ' / 142%'),
    ('Residual land value (at 18% margin)', '$1,761 / m2'),
], split=0.52, bold={'Development profit', 'Development margin', 'Residual land value (at 18% margin)'})
y -= 14
y = flagbox(c, y, 'Key sensitivities - read pages 10 & 12',
            'The result depends on achieving design-premium prices that are high for Glen Eden '
            'and not yet supported by a confirmed local comparable; on the dual-key build cost '
            '(the swing variable); and on council’s treatment of the dual-key consent. A '
            'registered valuation, a genuine local comparable, a QS build estimate, and an early '
            'planner’s view are required before binding commitment. See conditions precedent '
            'on the final page.', height=66)
footer(c, 2); c.showPage()

# ----- P3 THE PRODUCT -----
y = H - MT
y = header(c, y, 'The Product', 'Two products, one design language, two buyer pools')
y = wrap(c, 'The scheme is conceived as a single branded community of 26 residences. The '
            'architecture is intentionally raw - exposed concrete and blockwork in a brutalist '
            'idiom - while the interiors are crafted, warm and highly resolved. Shared '
            '"colliding facilities" (laundry, lounge, office / co-work) deliver a '
            'connected-living experience and allow private footprints to stay compact and '
            'efficient.', ML + 2, y, CW - 4)
y -= 8
y = sect(c, y, 'POSITIONING')
y = bullet(c, 'Two products, deliberately.',
           '16 single one-bedroom residences (45 m2) reach owner-occupiers and investors; '
           '10 dual-key residences (45 m2, each two lockable ~20 m2 studios) target '
           'yield-focused investors. Two audiences, halved absorption risk.', y)
y = bullet(c, 'Income-justified pricing.',
           'A dual-key generates two rental streams (~$640/week, ~$33,280/year) versus '
           '~$480/week for a one-bedroom - 33% more income per title. At $599,000 it yields '
           '5.6% gross, ahead of the one-bedroom’s 5.0%, so the higher price is backed by '
           'income.', y)
y = bullet(c, 'Brutalist shell, smart interior.',
           'The structure is the finish - no cladding or plasterboard layer - keeping build '
           'cost efficient while spend concentrates on joinery, integrated storage, smart '
           'systems and light.', y)
y = bullet(c, 'Connected, shared, modern.',
           'Colliding facilities - shared laundry, lounge, office / co-work - deliver the '
           'connected-living promise and make compact private studios genuinely liveable.', y)
y -= 2
c.setStrokeColor(MID_GREEN); c.setLineWidth(0.5); c.line(ML + 2, y, W - MR - 2, y); y -= 13
c.setFont('Helvetica-Bold', 7.5); c.setFillColor(TEXT_MID)
c.drawString(ML + 2, y, 'Interior design'); y -= 11
y = wrap(c, 'Interior design intent by Studio 11:11 (a Citadel design partner). The building '
            'architecture is to be prepared by a registered architect to be appointed.',
            ML + 2, y, CW - 4, size=8, lead=11, colour=TEXT_MID)
y -= 6
c.setFont('Helvetica-Bold', 7.5); c.setFillColor(TEXT_MID)
c.drawString(ML + 2, y, 'Tenure / operating model'); y -= 11
y = wrap(c, 'Amenity-rich, dual-key product can suit build-to-hold-and-operate as readily as '
            'build-to-sell. If sold as individual titles, ownership and operation of shared '
            'facilities must be resolved in the body-corporate structure. A build-to-hold model '
            'should be run alongside build-to-sell.', ML + 2, y, CW - 4, size=7.5, lead=10.5,
         colour=TEXT_LIGHT)
footer(c, 3); c.showPage()

# ----- P4 DESIGN PRECEDENTS (reference imagery, not this scheme) -----
y = H - MT
y = header(c, y, 'Design Precedents',
           'Existing developments - reference imagery only, not this scheme')
y = wrap(c, 'The design language is grounded in built West Auckland precedent: a raw '
            'board-formed concrete shell warmed by timber and signalled by a brick-red '
            'entry, with shared "colliding" amenity at its heart. The photographs below '
            'are existing, third-party developments shown to convey that intent.',
         ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 8
# Hyde (landscape) centred
_, hw, hh = pimg(c, 'hyde-street.png', ML + 2, y, CW - 4, 196)
y = y - hh - 9
c.setFont('Helvetica', 7.2); c.setFillColor(TEXT_LIGHT)
c.drawCentredString(ML + CW / 2.0, y,
                    'Hyde - board-formed concrete walk-up on an arterial frontage (existing development; reference only).')
y -= 14
# Two Glen Eden portraits side by side
box_w = (CW - 16) / 2.0
top = y
pimg(c, 'glen-eden-grid.png', ML + 2, top, box_w, 290)
pimg(c, 'glen-eden-montage.png', ML + 10 + box_w, top, box_w, 290)
y = top - 290 - 7
c.setFont('Helvetica', 7.2); c.setFillColor(TEXT_LIGHT)
c.drawCentredString(ML + CW / 2.0, y,
                    'The Glen Eden Co-Living - concrete shell, brick-red doors, timber warmth, shared courtyard & rooftop (existing development).')
y -= 16
y = flagbox(c, y, 'Important - these are not the proposed scheme',
            'Imagery on this page shows existing, third-party developments, included only to '
            'illustrate the intended design language. They are NOT the proposed building, not '
            'to scale, and not architecture by Citadel. The building design is to be prepared '
            'by the appointed registered architect. For internal reference.', height=52)
footer(c, 4); c.showPage()

# ----- P5 INDICATIVE MASSING & SITE - SCHEMATIC -----
y = H - MT
y = header(c, y, 'Indicative Massing & Site', 'Schematic - not to scale, not for consent')
y = wrap(c, 'The THAB zone permits 16 m height and 50% building coverage. A four-level walk-up '
            'at approximately 13 m sits under the height limit and avoids the cost of a lift and '
            'basement - the key efficiency of this typology. The diagrams below are schematic '
            'studies of the planning envelope only.', ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 6
# site plan (left) + axonometric (right), side by side — each its own caption
half = (CW - 14) / 2.0
top = y
(_, info_s) = figure(c, top, 'site_plan.png', half, x=ML + 2, max_h=222, caption=False)
(_, info_a) = figure(c, top, 'massing_axo.png', half, x=ML + 8 + half, max_h=222, caption=False)
xs, ws, hs = info_s
xa, wa, ha = info_a
ys = wrap_center(c, CAP, xs + ws / 2.0, top - hs - 7, ws + 24)
ya = wrap_center(c, CAP, xa + wa / 2.0, top - ha - 7, wa + 24)
y = min(ys, ya) - 6
# stacking (full width, compact)
y, _ = figure(c, y, 'stacking.png', CW - 60, max_h=120)
y -= 6
y = sect(c, y, 'ENVELOPE FACTS')
y = kv(c, y, [
    ('Site area', '809 m2'),
    ('Building coverage (50%)', '404 m2 footprint'),
    ('Levels', '4 (no lift, ~13 m)'),
    ('Gross building area', '~1,537 m2'),
    ('Net saleable (84% walk-up efficiency)', '~1,176 m2'),
    ('Gross floor area (GFA)', '~1,530 m2'),
    ('Residences', '26 (16 one-bed + 10 dual-key)'),
], split=0.60, rh=13)
y -= 8
c.setFont('Helvetica-Bold', 8.5); c.setFillColor(BLACK)
y = wrap(c, 'Any scheme denser than the existing 2020 consent (10 apartments) requires a fresh '
            'resource consent - allowed at $110,000 and ~6-12 months in the feasibility.',
         ML + 2, y, CW - 4, font='Helvetica-Bold', size=8.5, lead=11, colour=BLACK)
footer(c, 5); c.showPage()

# ----- P5 INDICATIVE UNIT LAYOUTS - SCHEMATIC -----
y = H - MT
y = header(c, y, 'Indicative Unit Layouts', 'Schematic - labelled zones, not detailed design')
y -= 2
y = sect(c, y, 'ONE-BEDROOM RESIDENCE (45 m2)')
y, _ = figure(c, y, 'plate_1bed.png', CW - 70, max_h=210)
y -= 8
y = sect(c, y, 'DUAL-KEY RESIDENCE (45 m2, two lockable studios)')
y, _ = figure(c, y, 'plate_dualkey.png', CW - 70, max_h=210)
y -= 6
y = wrap(c, 'The dual-key residence is a single title comprising two independently lockable '
            'studios served by a shared entry - sold as one dwelling, capable of two tenancies. '
            'Layouts are schematic and indicative only.', ML + 2, y, CW - 4, size=8.5, lead=11.5,
         colour=TEXT_MID)
footer(c, 6); c.showPage()

# ----- P6 INDICATIVE ELEVATION - SCHEMATIC -----
y = H - MT
y = header(c, y, 'Indicative Elevation', 'Schematic - massing rhythm, not to scale')
y = wrap(c, 'A diagrammatic four-level street elevation showing the brutalist massing rhythm: '
            'a regular window module across the three residential levels above a distinct '
            'ground-floor amenity frontage and entry.', ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 8
y, _ = figure(c, y, 'elevation.png', CW - 20, max_h=300)
y -= 10
c.setFont('Helvetica-Bold', 7.5); c.setFillColor(TEXT_MID)
c.drawString(ML + 2, y, 'Material note'); y -= 12
y = wrap(c, 'Brutalist expression - board-formed or precast concrete and exposed blockwork, '
            'with the structure as the finished surface. Material and detailed design to be '
            'developed by the appointed architect.', ML + 2, y, CW - 4, size=8.5, lead=11.5,
         colour=TEXT_MID)
footer(c, 7); c.showPage()

# ----- P7 UNIT SCHEDULE & MIX -----
y = H - MT
y = header(c, y, 'Unit Schedule & Mix', 'Two products across 26 titles')
y -= 4
colx = [ML + 8, ML + 205, ML + 270, ML + 355, ML + 420, W - MR - 8]
aligns = ['l', 'r', 'r', 'r', 'r', 'r']
headers = ['Product', 'Qty', 'Size', 'Price (incl)', '$/m2', 'GRV (incl)']
rows = [
    ['1-bed (single)', '16', '45 m2', '$499,000', '$11,089', '$7,984,000'],
    ['Dual-key (2 x 20 m2)', '10', '45 m2', '$599,000', '$13,311', '$5,990,000'],
    ['Total', '26', '', '', '', '$13,974,000'],
]
y = coltable(c, y, headers, rows, colx, aligns, total_idx=2, rowh=16, headh=16)
y -= 6
y = wrap(c, '26 titles; 36 lettable tenancies (16 one-beds + 20 studios). The dual-key '
            'residences each count as one consentable title but two lockable, separately '
            'tenantable studios.', ML + 2, y, CW - 4, size=8.5, lead=11.5, colour=TEXT_MID)
y -= 10
y = sect(c, y, 'WHY THE MIX')
y = wrap(c, 'The 60/40 split (16 one-bed / 10 dual-key) is the balanced choice: it spreads the '
            'sell-down across owner-occupiers and yield investors without over-concentrating the '
            'harder-to-sell investor product. Skewing further to dual-key lifts margin slightly '
            '(higher price point) but concentrates absorption risk; see the mix sensitivity on '
            'the following pages.', ML + 2, y, CW - 4, size=8.5, lead=11.5)
footer(c, 8); c.showPage()

# ----- P8 FEASIBILITY -----
y = H - MT
y = header(c, y, 'Feasibility', 'Adopted base case (ex-GST, $605,000 land entry)')
y = wrap(c, 'Full development feasibility, ex-GST, at Citadel’s $605,000 land entry. Build '
            'is a blended $3,726 / m2 - a $3,600 / m2 rate for the one-bedroom product and '
            '$4,000 / m2 for the dual-key product (two compact wet areas per title) - with a '
            'separate $350,000 allowance for the colliding-facilities fit-out.',
         ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 10
f = DATA['feasibility_ex_gst']
y = mtable(c, y, [
    ('Land entry', money(f['land_entry'])),
    ('Demolition to slab', money(f['demolition'])),
    ('Build (blended $3,726/m2 x 1,530 m2)', money(f['build'])),
    ('Colliding facilities fit-out', money(f['colliding_facilities_fitout'])),
    ('Professional fees (10%)', money(f['professional_fees'])),
    ('Contingency (6.5%)', money(f['contingency'])),
    ('Development contributions ($25k x 26 titles)', money(f['dev_contributions'])),
    ('Resource consent (fresh)', money(f['resource_consent_fresh'])),
    ('Siteworks (no basement)', money(f['siteworks'])),
    ('Construction finance (14 mo @ 7%, 50% avg drawn)', money(f['finance'])),
    ('Sales & marketing (3.5%)', money(f['sales_marketing'])),
], total=('Total development cost', money(f['total_cost'])))
y -= 4
y = mtable(c, y, [
    ('Gross realisation (26 residences, incl GST)', money(f['grv_incl'])),
    ('Gross realisation (ex-GST)', money(f['grv_ex'])),
])
y -= 4
y = bar(c, y, 'Development profit', money(f['profit']))
y -= 4
y = kv(c, y, [
    ('Development margin', '24.7%'),
    ('Equity required (25%)', money(f['equity'])),
    ('Return on equity', '142%'),
    ('Residual land value (at 18% margin)', '$1,761 / m2  (vs $1,400 / m2 ask: +$361 / m2)'),
    ('Programme', '~14 months'),
], split=0.50, bold={'Development margin', 'Return on equity', 'Residual land value (at 18% margin)'})
footer(c, 9); c.showPage()

# ----- P9 INVESTOR YIELD & SENSITIVITY -----
y = H - MT
y = header(c, y, 'Investor Yield & Sensitivity', 'Why the prices hold, and what moves them')
y = wrap(c, 'The scheme’s pricing is anchored in income. Both products yield above the '
            '~3-4% typical of Auckland residential, and the dual-key’s two income streams '
            'justify its premium.', ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 8
y = sect(c, y, 'INVESTOR YIELD')
colx = [ML + 8, ML + 250, ML + 380, W - MR - 8]
aligns = ['l', 'r', 'r', 'r']
y = coltable(c, y, ['Product', 'Rent', 'Annual gross', 'Gross yield'], [
    ['1-bed @ $499k', '$480 / wk', '$24,960', '5.0%'],
    ['Dual-key @ $599k (2 studios)', '$640 / wk', '$33,280', '5.6%'],
], colx, aligns, rowh=15)
y -= 10
y = sect(c, y, 'BUILD-COST SENSITIVITY (the swing variable - computed via model_logic.py)')
y = wrap(c, 'Build cost is the swing variable - the dual-key fit-out in particular. A $500 / m2 '
            'movement in the dual-key build rate moves the margin roughly 2-3 points and the '
            'land value by ~$400 / m2. A QS estimate is the single most important figure to '
            'confirm.', ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 6
colx = [ML + 8, ML + 200, ML + 360, W - MR - 8]
aligns = ['l', 'r', 'r', 'r']
y = coltable(c, y, ['Dual-key build $/m2', 'Blended $/m2', 'Scheme margin', 'Land /m2'], [
    ['$3,800', '$3,655', '25.8%', '$1,922'],
    ['$4,000  (adopted)', '$3,726', '24.7%', '$1,761'],
    ['$4,300', '$3,832', '23.1%', '$1,520'],
], colx, aligns, highlight_idx=1, rowh=15)
y -= 12
y = sect(c, y, 'MIX SENSITIVITY (vary the 60/40 split, total 26 - computed)')
colx = [ML + 8, ML + 260, W - MR - 8]
aligns = ['l', 'r', 'r']
y = coltable(c, y, ['Split (of 26)', 'Margin', 'Land /m2'], [
    ['18 x 1-bed + 8 dual-key  (69/31)', '24.1%', '$1,657'],
    ['16 x 1-bed + 10 dual-key  (62/38, adopted)', '24.7%', '$1,761'],
    ['14 x 1-bed + 12 dual-key  (54/46)', '25.3%', '$1,865'],
], colx, aligns, highlight_idx=1, rowh=15)
y -= 4
y = wrap(c, 'More dual-key slightly lifts margin and land value (higher price point) but '
            'concentrates the harder-to-sell investor product. The adopted 60/40 split is the '
            'balanced choice.', ML + 2, y, CW - 4, size=8, lead=10.5, colour=TEXT_MID)
footer(c, 10); c.showPage()

# ----- P10 MARKET ASSESSMENT -----
y = H - MT
y = header(c, y, 'Market Assessment', 'Demand, supply, and the premium question')
y = wrap(c, 'Glen Eden is an established West Auckland suburb 20 minutes from the CBD on the '
            'Western rail line. Median sale price is $823,833 (REINZ, 12 months to June 2026), '
            'median 33 days to sale, 282 dwellings sold. The market is steady and value-led - '
            'predominantly first-home buyers and investors.', ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 8
y = sect(c, y, 'DEMAND SIGNAL')
y = kv(c, y, [
    ('Median sale price (all stock, 12 mo)', '$823,833'),
    ('Median days to sale', '33 days'),
    ('Dwellings sold (12 mo)', '282'),
    ('Median rent (1-2 bed)', '$560-620 / week'),
    ('Buyer profile', 'First-home buyers & investors'),
], split=0.56)
y -= 10
y = sect(c, y, 'THE PREMIUM QUESTION - HONEST READ')
y = wrap(c, 'Design-led product commands clear premiums in amenity-rich, transport-central '
            'locations (Ponsonby, city fringe, Britomart). Glen Eden is a solid, affordable, '
            'family-and-investor market. The brand, the design and the dual-income hook improve '
            'both price and absorption - but they do not fully override the postcode. This is '
            'the central commercial risk, and the reason the prices must be validated against a '
            'real comparable before commitment.', ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 8
y = sect(c, y, 'SUPPLY & ABSORPTION')
y = wrap(c, 'New townhouse supply is active (e.g. Creston Group, 39 Brandon Road, 12 units), '
            'absorbed via investor yield guarantees and first-home-buyer deposit support - '
            'evidence of a price-sensitive market. The two-product mix directly addresses '
            'absorption: 16 one-bedrooms to a broad buyer pool and 10 dual-keys to yield '
            'investors spreads the sell-down across audiences rather than concentrating it.',
         ML + 2, y, CW - 4, size=8.5, lead=11.5)
footer(c, 11); c.showPage()

# ----- P11 FINANCING & RECOMMENDATION -----
y = H - MT
y = header(c, y, 'Financing & Recommendation', 'Capital stack and the path forward')
y = sect(c, y, 'CAPITAL STACK (EX-GST)')
y = mtable(c, y, [
    ('Total development cost', money(f['total_cost'])),
    ('Senior construction debt (75% LVR)', money(f['loan'])),
    ('Equity required (25%)', money(f['equity'])),
    ('Construction finance rate', '7.0% p.a.'),
    ('Programme', '~14 months'),
    ('Gross realisation (ex-GST)', money(f['grv_ex'])),
    ('Development profit', money(f['profit'])),
], total=('Development margin', '24.7%'))
y -= 8
y = sect(c, y, 'STRATEGY OPTIONS')
y = kv(c, y, [
    ('Build-to-sell (modelled)', '24.7% margin, 142% ROE'),
    ('Build-to-hold-and-operate', 'Rental + management margin - to model'),
    ('Sell consented site (flip)', 'Lower risk, lower return - see vendor IM'),
], split=0.44, rh=14)
y -= 8
y = sect(c, y, 'WHERE THIS SITS')
colx = [ML + 8, ML + 320, W - MR - 8]
aligns = ['l', 'r', 'r']
y = coltable(c, y, ['Scheme', 'Margin', 'Land /m2'], [
    ['Plain brutalist 28u @ $449k', '34.1%', '$2,920'],
    ['Design co-living 28u @ $489k', '27.1%', '$2,091'],
    ['Mixed 60/40 @ $499k/$599k (this scheme)', '24.7%', '$1,761'],
    ['Dual-key all 26t @ $549k', '22.2%', '$1,392'],
    ['Consented 10u townhouse (RC done)', '29.2%', '$1,537'],
], colx, aligns, highlight_idx=2, rowh=14)
y -= 10
y = bar(c, y, 'Recommendation', '')
y -= 4
y = wrap(c, 'The mixed scheme is the recommended development concept for the site. It balances '
            'return (24.7% margin, 142% ROE), supports a land value above the acquisition price '
            '($1,761 / m2 vs $1,400 / m2), and de-risks the sell-down by addressing two buyer '
            'pools - owner-occupiers and yield-focused investors. It is recommended for '
            'advancement to concept design, subject to the conditions precedent below.',
         ML + 2, y, CW - 4, size=8.5, lead=11.5)
y -= 4
c.setFont('Helvetica-Bold', 8); c.setFillColor(FLAG)
c.drawString(ML + 2, y, 'Conditions precedent'); y -= 12
cps = [
    'Registered valuation confirming one-bedroom and dual-key end values.',
    'At least one genuine local comparable supporting the $499,000 / $599,000 prices.',
    'QS build estimate, with particular focus on the dual-key fit-out rate.',
    'Early planner’s view on dual-key consent treatment (one dwelling per title, parking, '
    'and any short-stay use), and confirmation the 2020 consent can be superseded with a fresh '
    'consent pathway scoped.',
    'A build-to-hold operating model run alongside build-to-sell.',
    'Body-corporate / shared-facilities ownership and operating structure resolved.',
]
for i, t in enumerate(cps, 1):
    y = wrap(c, f'{i}.  {t}', ML + 6, y, CW - 8, size=8, lead=10.5, colour=TEXT_MID)
    y -= 1
y -= 6
c.setStrokeColor(TEXT_LIGHT); c.setLineWidth(0.4); c.line(ML + 2, y, W - MR - 2, y); y -= 11
y = wrap(c, 'Indicative concept information only. Not a registered valuation, not architecture, '
            'and not an offer. All figures subject to verification, due diligence, QS estimate, '
            'valuation, and contract. Schematic diagrams are not to scale and not for '
            'construction or resource consent. E&OE.', ML + 2, y, CW - 4, size=7,
         lead=9.5, colour=TEXT_LIGHT)
footer(c, 12); c.showPage()

c.save()
print('PDF written:', OUT, '-', os.path.getsize(OUT), 'bytes')
